.\"Copyright 2010 (c) EPFL
.TH RTF_GET_VERSION 3 2010 "EPFL" "rtfilter library"
.SH NAME
rtf_get_version - Returns the version of the library
.SH SYNOPSIS
.LP
.B #include <rtfilter.h>
.sp
.BI "size_t rtf_get_version(char *" string ", size_t " len ", int " line ");"
.br
.SH DESCRIPTION
.LP
This function fills in \fIstring\fP the version of the library if \fIline\fP
is 0. It fills at most \fIlen\fP character in \fIstring\fP including the
terminating null byte ('\0'). If the implementation of library depends on
other non-standard libraries, it will returns the version of them in
subsequent lines (\fIline\fP > 0). If there is no more dependency, nothing
is copied on \fIstring\fP and 0 is returned by the function.
.SH "RETURN VALUE"
.LP
Returns the number of characters copied on \fIstring\fP.


