.TH RTF_FILTER_COMBINE 3 "2019" "MINDMAZE" "rtfilter library"
.SH NAME
rtf_filter_combine \- combine vector of filters into one
.SH SYNOPSIS
.LP
.B #include <rtfilter.h>
.sp
.BI "struct rtf_filter * rtf_filter_combine(int " nfilters ",
.br
.BI "                                       struct rtf_filter ** " filters ")
.br
.SH DESCRIPTION
.LP
Combines the \fInfilters\fP rtf_filters structures into a single one. This is
so that a sequence of filters can be manipulated more easily.
.LP
On success, the combination-filter assumes ownership of all the filters
passed as arguments.
.SH "RETURN VALUE"
.LP
Returns a pointer to rtf_filter structure handling the combination, or a NULL
pointer on error.
.SH "SEE ALSO"
.LP
.BR rtf_filter (3),
.BR rtf_create_filter (3)

.SH AUTHOR
Gabriel Ganne <gabriel.ganne@mindmaze.ch>
