.\"Copyright 2019 (c) MindMaze
.TH RTF_FILTER_SET_LAZY_INIT 3 2019 "MINDMAZE" "rtfilter library"
.SH NAME
rtf_filter_set_lazy_init - Sets the filter lazy-init flag
.SH SYNOPSIS
.LP
.B #include <rtfilter.h>
.sp
.BI "void rtf_filter_set_lazy_init(hfilter filt, int do_lazy_init);"
.br
.SH DESCRIPTION
.LP
Set the lazy-init state of the hfilter \fIfilt\fP to given value
\fIdo_lazy_init\fP.
If the filter lazy-inits, then on its first call, the first data is used
to initialize the filter by calling \fBrtf_init_filter()\fB.
.SH "SEE ALSO"
.BR rtf_create_filter (3)
.BR rtf_init_filter (3)

