.\"Copyright 2010 (c) EPFL
.TH RTF_INIT_FILTER 3 2010 "EPFL" "rtfilter library"
.SH NAME
rtf_init_filter - Reinitialize the filter with given data
.SH SYNOPSIS
.LP
.B #include <rtfilter.h>
.sp
.BI "void rtf_init_filter(hfilter " filt ", const void* " data ");"
.br
.SH DESCRIPTION
.LP
\fBrtf_init_filter\fP() initializes the internal states of the filter with
one sample of data as if the filter has been applied indefinitely to
constant data consisting by this only sample.
.LP
\fIdata\fP is allowed to be NULL. In such case, the filter is initialized
with null signals (i.e. initialized with an input full of 0.0 values).
.LP
If \fIdata\fP is not NULL, the array pointed by \fIdata\fP should be
organized the same way as it would be if used in a call to
\fBrtf_filter\fP(3) with one sample.
.SH "RETURN VALUE"
None.
.SH "SEE ALSO"
.BR rtf_create_filter (3),
.BR rtf_filter (3)

